# Generated by Django 4.0.3 on 2022-03-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Name', models.TextField(primary_key=True, serialize=False)),
                ('Password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posts_name', models.TextField()),
                ('Kata_link', models.TextField()),
                ('Post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.users')),
            ],
        ),
    ]
