# Generated by Django 4.0.3 on 2022-03-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
    ]
